---
- name: Ensure lingering directory exists '{{ login_lingering_systemd_path }}'
  ansible.builtin.file:
    path: "{{ login_lingering_systemd_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Check if login lingering is already enabled for '{{ login_lingering_user }}'
  ansible.builtin.stat:
    path: "{{ login_lingering_systemd_path }}/{{ login_lingering_user }}"
  register: lingering_file

- name: Enable lingering for '{{ login_lingering_user }}'
  ansible.builtin.command: "loginctl enable-linger {{ login_lingering_user }}"
  when: not lingering_file.stat.exists
  changed_when: true
