---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    virtualbox
platforms:
  - name: nginx-alma
    box: almalinux/9
    memory: 1024
    cpu: 2
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.56.101
  - name: nginx-ubuntu
    box: ubuntu/jammy64
    memory: 1024
    cpu: 2
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.56.102
