---
- name: Converge
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Ensure SELinux is configured
      ansible.builtin.include_role:
        name: moritzrp.ansible.selinux
    - name: Install Podman
      ansible.builtin.include_role:
        name: moritzrp.ansible.podman
      vars:
        podman_login_lingering_users:
          - root
