---
- name: Check if EPEL repo is already configured
  ansible.builtin.stat:
    path: "{{ epel_repo_path }}"
  register: epel_exists

- name: Install repository
  when: not epel_exists.stat.exists
  block:
    - name: Ensure GPG key is installed
      ansible.builtin.rpm_key:
        key: "{{ epel_repo_gpg_key_url }}"
        state: present

    - name: Ensure EPEL release is present
      ansible.builtin.dnf:
        name: "{{ epel_repo_url }}"
        state: present
